modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Despawning%20Eggs%20Hatch"
logoFile="icon.png"

[[mods]]
modId="despawningeggshatch"
version="4.1"
displayName="Despawning Eggs Hatch"
displayURL="https://curseforge.com/minecraft/mc-mods/despawning-eggs-hatch"
authors="Rick South"
description='''Allows chicken eggs on a hay block to hatch into a chick baby just before they despawn.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.despawningeggshatch]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"