modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Automatic%20Operator"
logoFile="icon.png"

[[mods]]
modId="automaticoperator"
version="1.0"
displayName="Automatic Operator"
displayURL="https://curseforge.com/minecraft/mc-mods/automatic-operator"
authors="Rick South"
description='''Automatically makes all or specific players OP in server environments when they log in.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.automaticoperator]]
    modId="collective"
    mandatory=true
    versionRange="[6.62,)"
    ordering="NONE"
    side="BOTH"