modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Recipe%20Commands"
logoFile="icon.png"

[[mods]]
modId="recipecommands"
version="3.0"
displayName="Recipe Commands"
displayURL="https://curseforge.com/minecraft/mc-mods/recipe-commands"
authors="Rick South"
description='''Adds the ability to receive the pattern and ingredients of any recipe via chat by a command.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.recipecommands]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"