modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Grass%20Seeds"
logoFile="icon.png"

[[mods]]
modId="grassseeds"
version="3.0"
displayName="Grass Seeds"
displayURL="https://curseforge.com/minecraft/mc-mods/grass-seeds"
authors="Rick South"
description='''Allows the use of wheat seeds to transform dirt blocks to grass blocks and to create (tall) grass on them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.grassseeds]]
    modId="collective"
    mandatory=true
    versionRange="[6.18,)"
    ordering="NONE"
    side="BOTH"