modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Humbling%20Bundle"
logoFile="icon.png"

[[mods]]
modId="humblingbundle"
version="2.0"
displayName="Humbling Bundle"
displayURL="https://curseforge.com/minecraft/mc-mods/humbling-bundle"
authors="Rick South"
description='''Doubles all dropped entity loot, inspired by the Binding of Isaac.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.humblingbundle]]
    modId="collective"
    mandatory=true
    versionRange="[6.31,)"
    ordering="NONE"
    side="BOTH"