modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Better%20Beacon%20Placement"
logoFile="icon.png"

[[mods]]
modId="betterbeaconplacement"
version="3.1"
displayName="Better Beacon Placement"
displayURL="https://curseforge.com/minecraft/mc-mods/better-beacon-placement"
authors="Rick South"
description='''Easily place beacon bases by right-clicking the beacon with a mineral block plus other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.betterbeaconplacement]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"