modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Shulker%20Colours"
logoFile="icon.png"

[[mods]]
modId="randomshulkercolours"
version="3.0"
displayName="Random Shulker Colours"
displayURL="https://curseforge.com/minecraft/mc-mods/random-shulker-colours"
authors="Rick South"
description='''Gives new shulker spawns a random shell colour based on a configurable list.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randomshulkercolours]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"