modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Mineral%20Chance"
logoFile="icon.png"

[[mods]]
modId="mineralchance"
version="3.1"
displayName="Mineral Chance"
displayURL="https://curseforge.com/minecraft/mc-mods/mineral-chance"
authors="Rick South"
description='''Adds a chance to find a random mineral inside a stone block when mining.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.mineralchance]]
    modId="collective"
    mandatory=true
    versionRange="[6.45,)"
    ordering="NONE"
    side="BOTH"