modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Nether%20Portal%20Spread"
logoFile="icon.png"

[[mods]]
modId="netherportalspread"
version="7.3"
displayName="Nether Portal Spread"
displayURL="https://curseforge.com/minecraft/mc-mods/nether-portal-spread"
authors="Rick South"
description='''Nether portals spread (custom) nether blocks to the overworld around the portal in a configurable radius.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.netherportalspread]]
    modId="collective"
    mandatory=true
    versionRange="[6.48,)"
    ordering="NONE"
    side="BOTH"