modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20GUI%20Followers"
logoFile="icon.png"

[[mods]]
modId="guifollowers"
version="3.2"
displayName="GUI Followers"
displayURL="https://curseforge.com/minecraft/mc-mods/gui-followers"
authors="Rick South"
description='''[Client] Shows a list in the GUI/HUD with all tamed non-sitting followers around the player.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.guifollowers]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"