modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Wool%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="wooltweaks"
version="3.1"
displayName="Wool Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/wool-tweaks"
authors="Rick South"
description='''Dye beds, wool blocks and beds with a right-click in the world. Adds wool to string recipe for all wool blocks and allows players to dye any colour wool block with any dye.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.wooltweaks]]
    modId="collective"
    mandatory=true
    versionRange="[6.49,)"
    ordering="NONE"
    side="BOTH"