modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Fire%20Spread%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="firespreadtweaks"
version="2.3"
displayName="Fire Spread Tweaks"
displayURL="https://curseforge.com/minecraft/mc-mods/fire-spread-tweaks"
authors="Rick South"
description='''Disables the default firespread, but does make fire go out on its own after a configurable delay.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.firespreadtweaks]]
    modId="collective"
    mandatory=true
    versionRange="[6.50,)"
    ordering="NONE"
    side="BOTH"