modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Crying%20Portals"
logoFile="icon.png"

[[mods]]
modId="cryingportals"
version="2.0"
displayName="Crying Portals"
displayURL="https://curseforge.com/minecraft/mc-mods/crying-portals"
authors="Rick South"
description='''Extends the blocks allowed for nether portal creation to use normal and crying obsidian.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.cryingportals]]
    modId="collective"
    mandatory=true
    versionRange="[6.21,)"
    ordering="NONE"
    side="BOTH"