modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Kelp%20Fertilizer"
logoFile="icon.png"

[[mods]]
modId="kelpfertilizer"
version="3.0"
displayName="Kelp Fertilizer"
displayURL="https://curseforge.com/minecraft/mc-mods/kelp-fertilizer"
authors="Rick South"
description='''Kelp seaweed has a cell structure that filters sea water for rich nutrients. It can now act as a fertilizer like bone meal.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.kelpfertilizer]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"