modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Transcending%20Trident"
logoFile="icon.png"

[[mods]]
modId="transcendingtrident"
version="4.0"
displayName="Transcending Trident"
displayURL="https://curseforge.com/minecraft/mc-mods/transcending-trident"
authors="Rick South"
description='''Improves the vanilla trident. Hold a water bucket to use riptide, which is more powerful.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.transcendingtrident]]
    modId="collective"
    mandatory=true
    versionRange="[6.7,)"
    ordering="NONE"
    side="BOTH"