modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Vanilla%20Zoom"
logoFile="icon.png"

[[mods]]
modId="vanillazoom"
version="2.0"
displayName="Vanilla Zoom"
displayURL="https://curseforge.com/minecraft/mc-mods/vanilla-zoom"
authors="Rick South"
description='''Adds a vanilla-style zoom hotkey using the spyglass item, client-side.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, TheNickm2, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.vanillazoom]]
    modId="collective"
    mandatory=true
    versionRange="[6.5,)"
    ordering="NONE"
    side="BOTH"