modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Giant%20Spawn"
logoFile="icon.png"

[[mods]]
modId="giantspawn"
version="4.6"
displayName="Giant Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/giant-spawn"
authors="Rick South"
description='''Allows the giant to spawn naturally and other tweaks.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.giantspawn]]
    modId="collective"
    mandatory=true
    versionRange="[6.61,)"
    ordering="NONE"
    side="BOTH"