modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Bouncier%20Beds"
logoFile="icon.png"

[[mods]]
modId="bouncierbeds"
version="2.1"
displayName="Bouncier Beds"
displayURL="https://curseforge.com/minecraft/mc-mods/bouncier-beds"
authors="Rick South"
description='''Makes players bounce configurably higher on beds and prevents fall damage on them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.bouncierbeds]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"