modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Villager%20Death%20Messages"
logoFile="icon.png"

[[mods]]
modId="villagerdeathmessages"
version="3.1"
displayName="Villager Death Messages"
displayURL="https://curseforge.com/minecraft/mc-mods/villager-death-messages"
authors="Rick South"
description='''Broadcasts an informational death message whenever a villager passes away.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.villagerdeathmessages]]
    modId="collective"
    mandatory=true
    versionRange="[6.57,)"
    ordering="NONE"
    side="BOTH"