modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Zombie%20Villagers%20From%20Spawner"
logoFile="icon.png"

[[mods]]
modId="zombievillagersfromspawner"
version="3.4"
displayName="Zombie Villagers From Spawner"
displayURL="https://curseforge.com/minecraft/mc-mods/zombie-villagers-from-spawner"
authors="Rick South"
description='''Puts back the ability for zombie spawners to spawn the villager variant, removed in 1.11.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.zombievillagersfromspawner]]
    modId="collective"
    mandatory=true
    versionRange="[6.57,)"
    ordering="NONE"
    side="BOTH"