modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Random%20Bone%20Meal%20Flowers"
logoFile="icon.png"

[[mods]]
modId="randombonemealflowers"
version="4.1"
displayName="Random Bone Meal Flowers"
displayURL="https://curseforge.com/minecraft/mc-mods/random-bone-meal-flowers"
authors="Rick South"
description='''Randomizes the flowers spawned by bone meal, allowing all (modded) types to spawn everywhere.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.randombonemealflowers]]
    modId="collective"
    mandatory=true
    versionRange="[6.56,)"
    ordering="NONE"
    side="BOTH"